In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv('Car_Tyres_Dataset.csv')
print(df.shape)
df.head(10)

(4350, 11)

,Brand,Model,Submodel,Tyre Brand,Serial No.,Type,Load Index,Size,Selling Price,Original Price,Rating
0,Maruti,Swift Dzire,LDI (Diesel),JKTyre,Taximaxx,Tubeless,85,165/80 R 14,"3,255","3,255",5.0
1,Maruti,Swift Dzire,LDI (Diesel),CEAT,Milage X3,Tubeless,85,165/80 R 14,"3,406","3,406",4.0
2,Maruti,Swift Dzire,LDI (Diesel),Apollo,Amazer 4G Life,Tubeless,85,165/80 R 14,"3,490","4,319",4.5
3,Maruti,Swift Dzire,LDI (Diesel),Continental,Comfort Contact CC6,Tubeless,85,165/80 R 14,"4,484","4,244",NaN
4,Maruti,Swift Dzire,LDI (Diesel),GoodYear,Assurance Duraplus 2,Tubeless,85,165/80 R 14,"3,025","3,025",4.2
5,Maruti,Swift Dzire,LDI (Diesel),JKTyre,Tornado,Tubeless,85,165/80 R 14,"3,103","3,103",4.3
6,Maruti,Swift Dzire,LDI (Diesel),Firestone,FR500,Tubeless,85,165/80 R 14,"3,135","3,135",NaN
7,Maruti,Swift Dzire,LDI (Diesel),JKTyre,Elanzo Touring,Tubeless,85,165/80 R 14,"3,255","3,255",4.1
8,Maruti,Swift Dzire,LDI (Diesel),BridgeStone,B-Series B290,Tubeless,85,165/80 R 14,"4,250","4,250",3.7
9,Maruti,Swift Dzire,LDI (Diesel),BridgeStone,Turanza T005,Tubeless,85,165/80 R 14,"4,272","4,272",3.8

In [2]:
# split Size column
df[['Tire_Width0', 'Tire_Size']] = df['Size'].str.split(' ', n=1, expand=True)
df = df.drop('Size', axis=1)

df['Tire_Width0'].unique()

array(['165/80', '185/70', '215/55', '185/65', '145/80', '195/55',
       '155/65', '215/60', '205/60', '165/70', '155/80', '155', '145/70',
       '225/70', '225/65', '205/70', '195/65', '175/70'], dtype=object)

In [3]:
df[['Tire_Width', 'Aspect_Rstio']] = df['Tire_Width0'].str.split('/', n=1, expand=True)
df = df.drop('Tire_Width0', axis=1)

df['Tire_Width'].unique()

array(['165', '185', '215', '145', '195', '155', '205', '225', '175'],
      dtype=object)

In [4]:
df['Aspect_Rstio'].unique()

array(['80', '70', '55', '65', '60', None], dtype=object)

In [5]:
df['Aspect_Rstio'].fillna(value=0, inplace=True)
df['Aspect_Rstio'].unique()

array(['80', '70', '55', '65', '60', 0], dtype=object)

In [6]:
df['Tire_Size'].unique()

array(['R 14', 'R 15', 'R 16', 'R 19', 'R 20', 'R 21', 'R 22', 'R 17',
       'R 23', 'R 24', 'R 25', 'R 26', 'R 27', 'R 28', 'R 29', 'R14',
       'R 12', 'R 13', 'R 18'], dtype=object)

In [7]:
# Define the split length as negative
split_length = -2

# Function to split the string
def split_string(s, length):
    # Use negative indexing to split
    return s[:length], s[length:]

# Apply the function and create new columns
df[['Const_type', 'Wheel_diam']] = df['Tire_Size'].apply(lambda x: pd.Series(split_string(x, split_length)))

# Display the updated DataFrame
df

,Brand,Model,Submodel,Tyre Brand,Serial No.,Type,Load Index,Selling Price,Original Price,Rating,Tire_Size,Tire_Width,Aspect_Rstio,Const_type,Wheel_diam
0,Maruti,Swift Dzire,LDI (Diesel),JKTyre,Taximaxx,Tubeless,85,"3,255","3,255",5.0,R 14,165,80,R,14
1,Maruti,Swift Dzire,LDI (Diesel),CEAT,Milage X3,Tubeless,85,"3,406","3,406",4.0,R 14,165,80,R,14
2,Maruti,Swift Dzire,LDI (Diesel),Apollo,Amazer 4G Life,Tubeless,85,"3,490","4,319",4.5,R 14,165,80,R,14
3,Maruti,Swift Dzire,LDI (Diesel),Continental,Comfort Contact CC6,Tubeless,85,"4,484","4,244",NaN,R 14,165,80,R,14
4,Maruti,Swift Dzire,LDI (Diesel),GoodYear,Assurance Duraplus 2,Tubeless,85,"3,025","3,025",4.2,R 14,165,80,R,14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4345,Maruti,Swift Deca,VXI,MRF,ZLX,Tubeless,85,"4,038","4,038",4.0,R 14,165,80,R,14
4346,Maruti,Swift Deca,VDI,UltraMile,UM 551,Tubeless,85,"4,045","4,045",3.0,R 14,165,80,R,14
4347,Maruti,Swift Deca,VXI,UltraMile,UM 551,Tubeless,85,"4,045","4,045",3.0,R 14,165,80,R,14
4348,Maruti,Swift Deca,VDI,Yokohama,Earth-1 E400,Tubeless,85,"3,904","3,904",3.0,R 14,165,80,R,14
4349,Maruti,Swift Deca,VXI,Yokohama,Earth-1 E400,Tubeless,85,"3,904","3,904",3.0,R 14,165,80,R,14

In [8]:
df['Const_type'] = df['Const_type'].str.replace(' ','')

df.Const_type.unique()

array(['R'], dtype=object)

In [9]:
df = df.drop('Tire_Size', axis=1)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4350 entries, 0 to 4349
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Brand           4350 non-null   object
 1   Model           4350 non-null   object
 2   Submodel        4350 non-null   object
 3   Tyre Brand      4350 non-null   object
 4   Serial No.      4350 non-null   object
 5   Type            4350 non-null   object
 6   Load Index      4350 non-null   int64
 7   Selling Price   4350 non-null   object
 8   Original Price  4350 non-null   object
 9   Rating          2248 non-null   float64
 10  Tire_Width      4350 non-null   object
 11  Aspect_Rstio    4350 non-null   object
 12  Const_type      4350 non-null   object
 13  Wheel_diam      4350 non-null   object
dtypes: float64(1), int64(1), object(12)
memory usage: 475.9+ KB

In [10]:
# 重新索引 DataFrame
df = df.rename(columns={'Brand ': 'Brand'})

new_order = ['Brand', 'Model', 'Submodel', 'Tyre Brand', 'Serial No.', 'Type',
       'Load Index', 'Tire_Width', 'Aspect_Rstio', 'Const_type', 'Wheel_diam', 'Rating', 'Selling Price', 'Original Price']
df = df[new_order]

df.head(10)

,Brand,Model,Submodel,Tyre Brand,Serial No.,Type,Load Index,Tire_Width,Aspect_Rstio,Const_type,Wheel_diam,Rating,Selling Price,Original Price
0,Maruti,Swift Dzire,LDI (Diesel),JKTyre,Taximaxx,Tubeless,85,165,80,R,14,5.0,"3,255","3,255"
1,Maruti,Swift Dzire,LDI (Diesel),CEAT,Milage X3,Tubeless,85,165,80,R,14,4.0,"3,406","3,406"
2,Maruti,Swift Dzire,LDI (Diesel),Apollo,Amazer 4G Life,Tubeless,85,165,80,R,14,4.5,"3,490","4,319"
3,Maruti,Swift Dzire,LDI (Diesel),Continental,Comfort Contact CC6,Tubeless,85,165,80,R,14,NaN,"4,484","4,244"
4,Maruti,Swift Dzire,LDI (Diesel),GoodYear,Assurance Duraplus 2,Tubeless,85,165,80,R,14,4.2,"3,025","3,025"
5,Maruti,Swift Dzire,LDI (Diesel),JKTyre,Tornado,Tubeless,85,165,80,R,14,4.3,"3,103","3,103"
6,Maruti,Swift Dzire,LDI (Diesel),Firestone,FR500,Tubeless,85,165,80,R,14,NaN,"3,135","3,135"
7,Maruti,Swift Dzire,LDI (Diesel),JKTyre,Elanzo Touring,Tubeless,85,165,80,R,14,4.1,"3,255","3,255"
8,Maruti,Swift Dzire,LDI (Diesel),BridgeStone,B-Series B290,Tubeless,85,165,80,R,14,3.7,"4,250","4,250"
9,Maruti,Swift Dzire,LDI (Diesel),BridgeStone,Turanza T005,Tubeless,85,165,80,R,14,3.8,"4,272","4,272"

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4350 entries, 0 to 4349
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Brand           4350 non-null   object
 1   Model           4350 non-null   object
 2   Submodel        4350 non-null   object
 3   Tyre Brand      4350 non-null   object
 4   Serial No.      4350 non-null   object
 5   Type            4350 non-null   object
 6   Load Index      4350 non-null   int64
 7   Tire_Width      4350 non-null   object
 8   Aspect_Rstio    4350 non-null   object
 9   Const_type      4350 non-null   object
 10  Wheel_diam      4350 non-null   object
 11  Rating          2248 non-null   float64
 12  Selling Price   4350 non-null   object
 13  Original Price  4350 non-null   object
dtypes: float64(1), int64(1), object(12)
memory usage: 475.9+ KB

In [12]:
df['Selling Price'] = df['Selling Price'].str.replace(',','').astype(int)

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4350 entries, 0 to 4349
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Brand           4350 non-null   object
 1   Model           4350 non-null   object
 2   Submodel        4350 non-null   object
 3   Tyre Brand      4350 non-null   object
 4   Serial No.      4350 non-null   object
 5   Type            4350 non-null   object
 6   Load Index      4350 non-null   int64
 7   Tire_Width      4350 non-null   object
 8   Aspect_Rstio    4350 non-null   object
 9   Const_type      4350 non-null   object
 10  Wheel_diam      4350 non-null   object
 11  Rating          2248 non-null   float64
 12  Selling Price   4350 non-null   int32
 13  Original Price  4350 non-null   object
dtypes: float64(1), int32(1), int64(1), object(11)
memory usage: 458.9+ KB

In [13]:
df['Tire_Width'] = df['Tire_Width'].astype(int)
df['Tire_Width'].unique()

array([165, 185, 215, 145, 195, 155, 205, 225, 175])

In [14]:
df['Wheel_diam'] = df['Wheel_diam'].astype(int)
df['Wheel_diam'].unique()

array([14, 15, 16, 19, 20, 21, 22, 17, 23, 24, 25, 26, 27, 28, 29, 12, 13,
       18])

In [15]:
new_var = round(df.groupby('Tyre Brand')['Rating'].mean().sort_values(ascending=False),1)
new_var

Tyre Brand
Firestone      5.0
Pirelli        4.9
JKTyre         4.5
CEAT           4.4
GoodYear       4.4
Apollo         4.3
Falken         4.3
BridgeStone    4.2
Yokohama       4.2
Michelin       4.1
MRF            4.0
Continental    4.0
UltraMile      3.9
Hankook        NaN
Kumho          NaN
Maxxis         NaN
Name: Rating, dtype: float64

In [16]:
# df[Rating] = df.astype({'a': int, "b": complex})
df['Rating'] = df['Rating'].fillna(3.9).astype(float)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4350 entries, 0 to 4349
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Brand           4350 non-null   object
 1   Model           4350 non-null   object
 2   Submodel        4350 non-null   object
 3   Tyre Brand      4350 non-null   object
 4   Serial No.      4350 non-null   object
 5   Type            4350 non-null   object
 6   Load Index      4350 non-null   int64
 7   Tire_Width      4350 non-null   int32
 8   Aspect_Rstio    4350 non-null   object
 9   Const_type      4350 non-null   object
 10  Wheel_diam      4350 non-null   int32
 11  Rating          4350 non-null   float64
 12  Selling Price   4350 non-null   int32
 13  Original Price  4350 non-null   object
dtypes: float64(1), int32(3), int64(1), object(9)
memory usage: 424.9+ KB

In [17]:
# pd.set_option('display.float_format', '{:.2f}'.format)
# using this to change scientic format to general
df.describe()

        Load Index   Tire_Width   Wheel_diam       Rating  Selling Price
count  4350.000000  4350.000000  4350.000000  4350.000000    4350.000000
mean     84.101609   173.551724    14.233563     4.105471    4724.982989
std       6.716769    19.693419     1.317297     0.539928    1848.303937
min      69.000000   145.000000    12.000000     1.900000    2248.000000
25%      79.000000   155.000000    13.000000     3.900000    3400.000000
50%      86.000000   175.000000    14.000000     3.900000    4300.000000
75%      88.000000   185.000000    15.000000     4.500000    5594.000000
max     106.000000   225.000000    29.000000     5.000000   20257.000000

In [18]:
df.describe(include='O')

,Brand,Model,Submodel,Tyre Brand,Serial No.,Type,Aspect_Rstio,Const_type,Original Price
count,4350,4350,4350,4350,4350,4350,4350,4350,4350
unique,1,34,178,16,114,2,6,1,371
top,Maruti,Ciaz,ZDI (Diesel),BridgeStone,Milage X3,Tubeless,65,R,"4,750"
freq,4350,634,225,610,196,4061,1696,4350,56

In [19]:
df.isna().sum()

Brand             0
Model             0
Submodel          0
Tyre Brand        0
Serial No.        0
Type              0
Load Index        0
Tire_Width        0
Aspect_Rstio      0
Const_type        0
Wheel_diam        0
Rating            0
Selling Price     0
Original Price    0
dtype: int64

In [20]:
df.isnull().sum()

Brand             0
Model             0
Submodel          0
Tyre Brand        0
Serial No.        0
Type              0
Load Index        0
Tire_Width        0
Aspect_Rstio      0
Const_type        0
Wheel_diam        0
Rating            0
Selling Price     0
Original Price    0
dtype: int64

In [21]:
for col in df.columns:
    if df[col].dtype == 'object':
        print(col)
        print(df[col].unique())
        print('\n')

Brand
['Maruti']


Model
['Swift Dzire' 'Kizashi' 'Swift  ' 'Swift' 'Swift ' 'Alto' 'Baleno'
 'Wagon R' 'Vitara Brezza' 'Celerio' 'Omni' 'Eeco' 'Ertiga' 'Ciaz' '800'
 'Alto K10' 'A-Star' 'Grand Vitara' 'Gypsy' 'Ritz' 'Swift Dzire 2008'
 'SX4' 'Zen Estilo' 'Esteem' 'Zen  ' 'Zen ' 'Zen' 'Celerio X' 'Dzire'
 'Fronx' 'Grand Vitara 2003-2007 XI' 'New Swift (2018)' 'Stingray'
 'Swift Deca']


Submodel
['LDI (Diesel)' 'LXI Option (Petrol)' 'LXI (Petrol)' 'VDI (Diesel)'
 'Vxi AT (Petrol)' 'VXI (Petrol)' 'ZDI (Diesel)' 'CVT' 'ZXI'
 'ZDI (Petrol) New' 'ZXI (Petrol) New' 'ZXI (Diesel) New'
 'VDI Windsong Limited Edition (Diesel)' 'Green LX' 'Green LXi (CNG)'
 'Green Std' 'LX' 'LXi' 'Std' '658 JDM' '800 Lx CNG' '800 Lxi Airbag'
 '800 Lxi CNG' '800 Std CNG' '800 VXI' '800 VXI Airbag' '800 VXI ' 'Vxi'
 'Vxi BS III' 'RS' 'Diesel' 'LX (Petrol)' 'LXI (CNG)' 'LXI (DUO)'
 'VXI with ABS (Petrol)' 'vxi (Petrol)' 'Diesel Ldl (0)' 'Diesel Ldi+'
 'Diesel Vdi+' 'Diesel ZDi +' 'LDi' 'VDi' 'VDi AMT' 'ZDi + AMT' 'VDi '
 'LDi ' 'Diesel LdI (0)' ' VDi' ' VDi AMT' 'Ldi' 'Green Vxi (CNG)'
 'Lxi AT (Petrol)' 'Zxi (Petrol)  ' 'Zxi Optional (Petrol)  '
 'Green Vxi (O)' 'Lxi MT' 'Lxi MT (O)' 'Vxi AMT (O)' 'Zxi AMT '
 'Zxi AMT (O)' 'Zxi AMT' 'Zxi Optional (Petrol)' 'Zxi (Petrol)' 'Lxi MT '
 'Lxi AT (Petrol) ' 'Zxi Optional (Petrol) ' 'E MPI STD'
 'LPG CARGO BSIII W IMMOBILISER' 'LPG STD BSIII 5 STR W IMMOBILISER'
 'MPI Ambulance' 'MPI CARGO' 'MPI STD' '5 Seater AC ( Petrol )'
 '5 Seater Standard ( Petrol )' '7 Seater Standard ( Petrol )'
 'Ambulance Petrol AC Plus HTR' 'CNG 5 Seater AC' 'CNG HTR 5 STR'
 'Flexi Green' '5 Seater CNG' 'LXI CNG (CNG)' 'VXI ABS (Petrol)'
 'VXI CNG (CNG)' 'ZXI (Petrol)' 'VXi AT Petrol' 'ZXi AT Petrol' 'ZXi+'
 'LXI CNG(CNG)' 'AT Vxi Plus (Petrol)' 'Zxi Plus(Petrol)'
 'DDiS 200 Smart Hybrid ALPHA' 'DDiS 225 ALPHA' 'K15 Smart Hybrid ALPHA'
 'K15 Smart Hybrid AT ALPHA' 'AT Zxi Plus (Petrol)' 'Vdi Plus (Diesel)'
 'Vdi(Diesel)' 'Vxi Plus (Petrol)' 'Vxi(Petrol)' 'Zxi(Petrol)'
 'DDiS 200 Smart Hybrid DELTA' 'DDiS 200 Smart Hybrid SIGMA'
 'DDiS 200 Smart Hybrid ZETA' 'DDiS 225 DELTA' 'DDiS 225 SIGMA'
 'DDiS 225 ZETA' 'K15 Smart Hybrid AT DELTA' 'K15 Smart Hybrid AT SIGMA'
 'K15 Smart Hybrid AT ZETA' 'K15 Smart Hybrid DELTA'
 'K15 Smart Hybrid SIGMA' 'K15 Smart Hybrid ZETA' 'Petrol' 'LX(Petrol)'
 'LXi [2010 - 2014]' 'VXi [2010 - 2014]' 'LXi CNG' 'VXi'
 'VXi AGS (Petrol)' 'VXi Option (Petrol)' 'LXI CNG (Petrol)' 'LXI(Petrol)'
 'VXi AMT' 'VXI(Petrol)' 'AT VXI' 'Lxi' 'Zxi' 'Zxi Optional' '2.4 AT'
 '2.4 AT (Petrol)' '2.4 MT' '2.4 MT (Petrol)'
 'King Hard Top Ambulance(Petrol)' 'King Hard Top MPI(Petrol)'
 'King Soft Top MPI(Petrol)' 'MT' 'AT(Petrol)' 'Lxi(Petrol)'
 'VDi (ABS)(Diesel)' 'VXi ABS(Petrol)' 'ZXI AT Leather(Petrol)'
 'ZXI AT(Petrol)' 'ZXI MT Leather(Petrol)' 'ZXI MT(Petrol)' 'VDI(Diesel)'
 'LXI Green (CNG)' 'VXI W/ ABS(Petrol)' 'AX BS II(Petrol)'
 'LX BS II(Petrol)' 'LX BS III(Petrol)' 'Lxi BS II(Petrol)'
 'Lxi BS III(Petrol)' 'LXi(Petrol)' 'AX(Petrol)' 'Vx BS II(Petrol)'
 'Vxi BS II(Petrol)' 'Vxi BS III(Petrol)' 'Vxi (O)' 'Vxi AGS'
 'Vxi AGS (O)' 'Zxi AGS' 'Zxi AGS (O)' 'ZDi+ MT' 'ZXi AMT' 'ZXi MT'
 'ZXi+ AMT' 'ZXi+ MT' '7 At' '7 Mt' 'VDi AGS' 'ZDi + AGS' 'ZDi AGS'
 'Zxi + AGS' 'ZXi AGS' 'ZXI+' 'Vxi AMT' 'VDI' 'VXI']


Tyre Brand
['JKTyre' 'CEAT' 'Apollo' 'Continental' 'GoodYear' 'Firestone'
 'BridgeStone' 'Falken' 'MRF' 'UltraMile' 'Yokohama' 'Kumho' 'Pirelli'
 'Michelin' 'Hankook' 'Maxxis']


Serial No.
['Taximaxx' 'Milage X3' 'Amazer 4G Life' 'Comfort Contact CC6'
 'Assurance Duraplus 2' 'Tornado' 'FR500' 'Elanzo Touring' 'B-Series B290'
 'Turanza T005' 'S-Series S248' 'Ecopia EP150' 'FuelSmart' 'Sincera845'
 'Duraplus' 'Assurance Duraplus' 'UX Royale' 'ZTX' 'ZV2K' 'ZLX' 'UM 551'
 'Earth-1 E400' 'Ecowing KH27' 'Cinturato P4' 'Energy XM2' 'Optimo ME02'
 'MAP3' 'Ainac 4G' 'Aspire 4G' 'Amazer 3G Maxx' 'B-series B250'
 'SecuraDrive' 'Comfort Contact CC5' 'Ultra Contact UC6' 'EcoRun ZE914'
 'Assurance Triplemax' 'Assurance Triplemax 2' 'ZLO' 'ZVTV' 'Cinturato P6'
 'BluEarth AE50' 'BluEarth-GT AE51' 'DB E70B' 'Amazer XL' 'Amazer 4G  '
 'Turanza ER60' 'Ducaro Hi-Miler' 'Optimo K715' 'Ultima XP' 'Ultima Neo'
 'Ultima XPC' 'Ultima NXT' 'ZCT' 'ZVTS' 'Ainac 4GS' 'B-Series B250'
 'ContiComfort Contact CC5' 'UltraContact UC6' 'ContiMax Contact MC5'
 'Sincera835' 'Ziex ZE914 EcoRun' 'Eagle F1 Directional 5' 'Optimo K415'
 'Ultima Sport' 'Primacy 4ST' 'Cinturato P1 Verde' 'S.Drive AS01'
 'AMAZER3G' 'FS100' 'GT3' 'Apterra Cross' 'Manchester United' 'Apterra HP'
 'Turanza T001' 'Potenza G3' 'Czar Sports' 'Czar HP' 'Azenis PT 722'
 'Excellence' 'Assurance Armorgrip' 'Elanzo Nxt' 'Ranger H/T' 'MS300'
 'BluEarth RV2' 'A348' 'Amazer 4G Eco' 'Duraplus DP-M1' 'Amazer 4G '
 'Altrust' 'L607' 'Milaze HD' 'Linam R 51' 'UM 787 LT' 'Duraplus ' 'ZCC'
 'S-Series S322' 'GPS2' 'Geolandar G92C' 'Scorpion Verde All Season'
 'Efficient Grip SUV' 'Dynapro HP (RA23)' 'Latitude Tour' 'Primacy SUV'
 'Geolandar SUV G055' 'Conti 4X4 Contact' 'Geolandar A/T G015'
 'Geolandar A/T G016' 'Cinturato P7' 'Victra I-Pro MA I-Pro'
 'Assurance Duraplus ' 'Eagle NCT5' 'Eagle F1 GSD3' 'ZVTSM' 'Milaze']


Type
['Tubeless' 'Tube']


Aspect_Rstio
['80' '70' '55' '65' '60' 0]


Const_type
['R']


Original Price
['3,255' '3,406' '4,319' '4,244' '3,025' '3,103' '3,135' '4,250' '4,272'
 '4,300' '4,150' '3,617' '3,637' '4,184' '3,423' '3,464' '3,288' '3,995'
 '4,014' '4,038' '4,045' '3,748' '3,800' '5,350' '5,170' '4,987' '5,200'
 '5,429' '5,359' '4,123' '4,366' '4,351' '4,489' '10,880' '4,688' '9,891'
 '5,000' '5,150' '5,196' '5,250' '6,450' '6,050' '6,111' '6,150' '4,377'
 '4,894' '5,202' '4,086' '5,257' '5,940' '5,699' '6,644' '5,526' '5,609'
 '5,332' '3,990' '4,608' '4,262' '4,618' '4,885' '4,724' '4,853' '4,638'
 '4,286' '4,313' '3,227' '3,385' '3,420' '4,896' '4,813' '5,875' '4,390'
 '4,736' '4,845' '5,269' '5,273' '4,345' '4,523' '20,257' '17,284' '6,540'
 '4,750' '3,455' '2,851' '2,857' '2,946' '2,781' '3,000' '3,150' '3,250'
 '3,400' '2,477' '2,583' '2,615' '2,773' '2,913' '2,328' '2,623' '2,465'
 '2,826' '3,181' '2,575' '2,520' '2,551' '2,397' '2,629' '2,702' '2,810'
 '2,838' '3,968' '2,608' '3,110' '2,985' '5,616' '6,824' '7,315' '4,950'
 '5,140' '8,000' '8,250' '8,350' '5,753' '4,407' '4,500' '5,772' '5,430'
 '7,921' '9,262' '6,887' '7,181' '4,662' '7,220' '4,410' '4,451' '4,641'
 '3,943' '4,467' '3,821' '6,763' '5,370' '9,110' '5,552' '9,088' '7,568'
 '7,840' '7,869' '8,033' '4,478' '3,325' '3,534' '3,696' '3,700' '3,417'
 '3,514' '3,757' '3,599' '2,850' '2,827' '3,138' '3,046' '3,983' '3,186'
 '3,348' '3,336' '8,985' '8,265' '8,334' '9,244' '7,399' '7,503' '10,062'
 '7,950' '8,150' '8,560' '5,829' '8,333' '6,781' '7,713' '7,959' '9,246'
 '7,748' '8,058' '8,096' '8,476' '7,240' '7,603' '7,929' '8,917' '6,466'
 '7,332' '7,781' '5,849' '6,239' '7,026' '7,095' '6,750' '8,500' '10,760'
 '8,990' '8,105' '9,345' '6,599' '5,760' '7,099' '7,515' '7,764' '10,148'
 '8,788' '9,116' '9,141' '9,209' '12,495' '3,303' '3,387' '4,027' '3,650'
 '4,274' '3,142' '3,279' '3,999' '3,870' '4,374' '2,499' '2,785' '2,945'
 '3,286' '3,465' '3,660' '3,048' '3,140' '4,290' '3,502' '3,073' '3,402'
 '3,628' '3,584' '3,802' '3,795' '3,843' '4,400' '3,643' '4,493' '3,611'
 '3,451' '4,275' '6,671' '5,374' '5,413' '5,594' '5,853' '9,292' '7,566'
 '7,837' '7,866' '8,194' '2,262' '2,947' '3,239' '2,248' '2,280' '2,324'
 '2,892' '2,967' '3,248' '3,155' '3,095' '3,693' '3,792' '3,300' '3,770'
 '2,759' '2,774' '2,984' '3,702' '3,824' '3,827' '3,312' '2,898' '2,999'
 '3,157' '3,208' '3,556' '2,678' '2,972' '3,044' '2,708' '2,713' '2,859'
 '2,697' '2,802' '2,862' '4,294' '3,401' '3,570' '3,529' '3,308' '3,088'
 '3,938' '10,471' '14,906' '15,493' '9,880' '10,099' '10,706' '11,695'
 '14,358' '14,963' '6,520' '6,754' '6,852' '7,172' '15,009' '13,754'
 '4,199' '4,484' '4,876' '3,904' '4,613' '4,729' '6,666' '6,280' '6,481'
 '6,350' '6,550' '6,650' '5,126' '6,639' '7,309' '5,300' '6,131' '5,514'
 '5,571' '5,603' '6,195' '5,193' '5,339' '7,273' '7,670' '9,170' '6,820'
 '6,365' '5,099' '7,437' '7,999' '7,685' '10,351' '6,223' '3,392' '2,915'
 '4,314' '4,859' '4,434' '4,144' '4,799' '4,973' '4,057' '4,060' '4,259'
 '4,619' '3,951' '3,583' '3,687' '3,732' '5,084' '4,580' '4,376' '3,527'
 '10,472' '3,496' '4,182' '3,497']

In [22]:
id = df[df['Model'] == 'Swift  '].index
df.loc[id, 'Model'] = df.loc[id, 'Model'].str.replace('  ','')
df.Model.unique()

array(['Swift Dzire', 'Kizashi', 'Swift', 'Swift ', 'Alto', 'Baleno',
       'Wagon R', 'Vitara Brezza', 'Celerio', 'Omni', 'Eeco', 'Ertiga',
       'Ciaz', '800', 'Alto K10', 'A-Star', 'Grand Vitara', 'Gypsy',
       'Ritz', 'Swift Dzire 2008', 'SX4', 'Zen Estilo', 'Esteem', 'Zen  ',
       'Zen ', 'Zen', 'Celerio X', 'Dzire', 'Fronx',
       'Grand Vitara 2003-2007 XI', 'New Swift (2018)', 'Stingray',
       'Swift Deca'], dtype=object)

In [23]:
id = df[df['Model'] == 'Zen  '].index
df.loc[id, 'Model'] = df.loc[id, 'Model'].str.replace('  ','')
df.Model.unique()

array(['Swift Dzire', 'Kizashi', 'Swift', 'Swift ', 'Alto', 'Baleno',
       'Wagon R', 'Vitara Brezza', 'Celerio', 'Omni', 'Eeco', 'Ertiga',
       'Ciaz', '800', 'Alto K10', 'A-Star', 'Grand Vitara', 'Gypsy',
       'Ritz', 'Swift Dzire 2008', 'SX4', 'Zen Estilo', 'Esteem', 'Zen',
       'Zen ', 'Celerio X', 'Dzire', 'Fronx', 'Grand Vitara 2003-2007 XI',
       'New Swift (2018)', 'Stingray', 'Swift Deca'], dtype=object)

In [24]:
id = df[df['Model'] == 'Zen '].index
df.loc[id, 'Model'] = df.loc[id, 'Model'].str.replace(' ','')
df.Model.nunique()

31

In [25]:
# Amazer 4G, Assurance Duraplus, B-Series B250, Duraplus, Ultra Contact UC6, UltraContact UC6, 'Comfort Contact CC5 ContiComfort Contact CC5'

In [26]:
# Amazer 4G

id = df[df['Serial No.'] == 'Amazer 4G  '].index
df.loc[id, 'Serial No.'] = df.loc[id, 'Serial No.'].str.replace('  ','')

df['Serial No.'].sort_values().unique()

array(['A348', 'AMAZER3G', 'Ainac 4G', 'Ainac 4GS', 'Altrust',
       'Amazer 3G Maxx', 'Amazer 4G', 'Amazer 4G ', 'Amazer 4G Eco',
       'Amazer 4G Life', 'Amazer XL', 'Apterra Cross', 'Apterra HP',
       'Aspire 4G', 'Assurance Armorgrip', 'Assurance Duraplus',
       'Assurance Duraplus ', 'Assurance Duraplus 2',
       'Assurance Triplemax', 'Assurance Triplemax 2', 'Azenis PT 722',
       'B-Series B250', 'B-Series B290', 'B-series B250', 'BluEarth AE50',
       'BluEarth RV2', 'BluEarth-GT AE51', 'Cinturato P1 Verde',
       'Cinturato P4', 'Cinturato P6', 'Cinturato P7',
       'Comfort Contact CC5', 'Comfort Contact CC6', 'Conti 4X4 Contact',
       'ContiComfort Contact CC5', 'ContiMax Contact MC5', 'Czar HP',
       'Czar Sports', 'DB E70B', 'Ducaro Hi-Miler', 'Duraplus',
       'Duraplus ', 'Duraplus DP-M1', 'Dynapro HP (RA23)',
       'Eagle F1 Directional 5', 'Eagle F1 GSD3', 'Eagle NCT5',
       'Earth-1 E400', 'EcoRun ZE914', 'Ecopia EP150', 'Ecowing KH27',
       'Efficient Grip SUV', 'Elanzo Nxt', 'Elanzo Touring', 'Energy XM2',
       'Excellence', 'FR500', 'FS100', 'FuelSmart', 'GPS2', 'GT3',
       'Geolandar A/T G015', 'Geolandar A/T G016', 'Geolandar G92C',
       'Geolandar SUV G055', 'L607', 'Latitude Tour', 'Linam R 51',
       'MAP3', 'MS300', 'Manchester United', 'Milage X3', 'Milaze',
       'Milaze HD', 'Optimo K415', 'Optimo K715', 'Optimo ME02',
       'Potenza G3', 'Primacy 4ST', 'Primacy SUV', 'Ranger H/T',
       'S-Series S248', 'S-Series S322', 'S.Drive AS01',
       'Scorpion Verde All Season', 'SecuraDrive', 'Sincera835',
       'Sincera845', 'Taximaxx', 'Tornado', 'Turanza ER60',
       'Turanza T001', 'Turanza T005', 'UM 551', 'UM 787 LT', 'UX Royale',
       'Ultima NXT', 'Ultima Neo', 'Ultima Sport', 'Ultima XP',
       'Ultima XPC', 'Ultra Contact UC6', 'UltraContact UC6',
       'Victra I-Pro MA I-Pro', 'ZCC', 'ZCT', 'ZLO', 'ZLX', 'ZTX', 'ZV2K',
       'ZVTS', 'ZVTSM', 'ZVTV', 'Ziex ZE914 EcoRun'], dtype=object)

In [27]:
id = df[df['Serial No.'] == 'Amazer 4G '].index
df.loc[id, 'Serial No.'] = df.loc[id, 'Serial No.'].str.replace(' ','')

df['Serial No.'].sort_values().unique()

array(['A348', 'AMAZER3G', 'Ainac 4G', 'Ainac 4GS', 'Altrust',
       'Amazer 3G Maxx', 'Amazer 4G', 'Amazer 4G Eco', 'Amazer 4G Life',
       'Amazer XL', 'Amazer4G', 'Apterra Cross', 'Apterra HP',
       'Aspire 4G', 'Assurance Armorgrip', 'Assurance Duraplus',
       'Assurance Duraplus ', 'Assurance Duraplus 2',
       'Assurance Triplemax', 'Assurance Triplemax 2', 'Azenis PT 722',
       'B-Series B250', 'B-Series B290', 'B-series B250', 'BluEarth AE50',
       'BluEarth RV2', 'BluEarth-GT AE51', 'Cinturato P1 Verde',
       'Cinturato P4', 'Cinturato P6', 'Cinturato P7',
       'Comfort Contact CC5', 'Comfort Contact CC6', 'Conti 4X4 Contact',
       'ContiComfort Contact CC5', 'ContiMax Contact MC5', 'Czar HP',
       'Czar Sports', 'DB E70B', 'Ducaro Hi-Miler', 'Duraplus',
       'Duraplus ', 'Duraplus DP-M1', 'Dynapro HP (RA23)',
       'Eagle F1 Directional 5', 'Eagle F1 GSD3', 'Eagle NCT5',
       'Earth-1 E400', 'EcoRun ZE914', 'Ecopia EP150', 'Ecowing KH27',
       'Efficient Grip SUV', 'Elanzo Nxt', 'Elanzo Touring', 'Energy XM2',
       'Excellence', 'FR500', 'FS100', 'FuelSmart', 'GPS2', 'GT3',
       'Geolandar A/T G015', 'Geolandar A/T G016', 'Geolandar G92C',
       'Geolandar SUV G055', 'L607', 'Latitude Tour', 'Linam R 51',
       'MAP3', 'MS300', 'Manchester United', 'Milage X3', 'Milaze',
       'Milaze HD', 'Optimo K415', 'Optimo K715', 'Optimo ME02',
       'Potenza G3', 'Primacy 4ST', 'Primacy SUV', 'Ranger H/T',
       'S-Series S248', 'S-Series S322', 'S.Drive AS01',
       'Scorpion Verde All Season', 'SecuraDrive', 'Sincera835',
       'Sincera845', 'Taximaxx', 'Tornado', 'Turanza ER60',
       'Turanza T001', 'Turanza T005', 'UM 551', 'UM 787 LT', 'UX Royale',
       'Ultima NXT', 'Ultima Neo', 'Ultima Sport', 'Ultima XP',
       'Ultima XPC', 'Ultra Contact UC6', 'UltraContact UC6',
       'Victra I-Pro MA I-Pro', 'ZCC', 'ZCT', 'ZLO', 'ZLX', 'ZTX', 'ZV2K',
       'ZVTS', 'ZVTSM', 'ZVTV', 'Ziex ZE914 EcoRun'], dtype=object)

In [28]:
# Assurance Duraplus

id = df[df['Serial No.'] == 'Assurance Duraplus '].index
df.loc[id, 'Serial No.'] = df.loc[id, 'Serial No.'].str.replace(' ','')

df['Serial No.'].sort_values().unique()

array(['A348', 'AMAZER3G', 'Ainac 4G', 'Ainac 4GS', 'Altrust',
       'Amazer 3G Maxx', 'Amazer 4G', 'Amazer 4G Eco', 'Amazer 4G Life',
       'Amazer XL', 'Amazer4G', 'Apterra Cross', 'Apterra HP',
       'Aspire 4G', 'Assurance Armorgrip', 'Assurance Duraplus',
       'Assurance Duraplus 2', 'Assurance Triplemax',
       'Assurance Triplemax 2', 'AssuranceDuraplus', 'Azenis PT 722',
       'B-Series B250', 'B-Series B290', 'B-series B250', 'BluEarth AE50',
       'BluEarth RV2', 'BluEarth-GT AE51', 'Cinturato P1 Verde',
       'Cinturato P4', 'Cinturato P6', 'Cinturato P7',
       'Comfort Contact CC5', 'Comfort Contact CC6', 'Conti 4X4 Contact',
       'ContiComfort Contact CC5', 'ContiMax Contact MC5', 'Czar HP',
       'Czar Sports', 'DB E70B', 'Ducaro Hi-Miler', 'Duraplus',
       'Duraplus ', 'Duraplus DP-M1', 'Dynapro HP (RA23)',
       'Eagle F1 Directional 5', 'Eagle F1 GSD3', 'Eagle NCT5',
       'Earth-1 E400', 'EcoRun ZE914', 'Ecopia EP150', 'Ecowing KH27',
       'Efficient Grip SUV', 'Elanzo Nxt', 'Elanzo Touring', 'Energy XM2',
       'Excellence', 'FR500', 'FS100', 'FuelSmart', 'GPS2', 'GT3',
       'Geolandar A/T G015', 'Geolandar A/T G016', 'Geolandar G92C',
       'Geolandar SUV G055', 'L607', 'Latitude Tour', 'Linam R 51',
       'MAP3', 'MS300', 'Manchester United', 'Milage X3', 'Milaze',
       'Milaze HD', 'Optimo K415', 'Optimo K715', 'Optimo ME02',
       'Potenza G3', 'Primacy 4ST', 'Primacy SUV', 'Ranger H/T',
       'S-Series S248', 'S-Series S322', 'S.Drive AS01',
       'Scorpion Verde All Season', 'SecuraDrive', 'Sincera835',
       'Sincera845', 'Taximaxx', 'Tornado', 'Turanza ER60',
       'Turanza T001', 'Turanza T005', 'UM 551', 'UM 787 LT', 'UX Royale',
       'Ultima NXT', 'Ultima Neo', 'Ultima Sport', 'Ultima XP',
       'Ultima XPC', 'Ultra Contact UC6', 'UltraContact UC6',
       'Victra I-Pro MA I-Pro', 'ZCC', 'ZCT', 'ZLO', 'ZLX', 'ZTX', 'ZV2K',
       'ZVTS', 'ZVTSM', 'ZVTV', 'Ziex ZE914 EcoRun'], dtype=object)

In [29]:
# B-series B250

id = df[df['Serial No.'] == 'B-series B250'].index
df.loc[id, 'Serial No.'] = df.loc[id, 'Serial No.'].str.replace('B-series B250','B-Series B250')
df['Serial No.'].sort_values().unique()

array(['A348', 'AMAZER3G', 'Ainac 4G', 'Ainac 4GS', 'Altrust',
       'Amazer 3G Maxx', 'Amazer 4G', 'Amazer 4G Eco', 'Amazer 4G Life',
       'Amazer XL', 'Amazer4G', 'Apterra Cross', 'Apterra HP',
       'Aspire 4G', 'Assurance Armorgrip', 'Assurance Duraplus',
       'Assurance Duraplus 2', 'Assurance Triplemax',
       'Assurance Triplemax 2', 'AssuranceDuraplus', 'Azenis PT 722',
       'B-Series B250', 'B-Series B290', 'BluEarth AE50', 'BluEarth RV2',
       'BluEarth-GT AE51', 'Cinturato P1 Verde', 'Cinturato P4',
       'Cinturato P6', 'Cinturato P7', 'Comfort Contact CC5',
       'Comfort Contact CC6', 'Conti 4X4 Contact',
       'ContiComfort Contact CC5', 'ContiMax Contact MC5', 'Czar HP',
       'Czar Sports', 'DB E70B', 'Ducaro Hi-Miler', 'Duraplus',
       'Duraplus ', 'Duraplus DP-M1', 'Dynapro HP (RA23)',
       'Eagle F1 Directional 5', 'Eagle F1 GSD3', 'Eagle NCT5',
       'Earth-1 E400', 'EcoRun ZE914', 'Ecopia EP150', 'Ecowing KH27',
       'Efficient Grip SUV', 'Elanzo Nxt', 'Elanzo Touring', 'Energy XM2',
       'Excellence', 'FR500', 'FS100', 'FuelSmart', 'GPS2', 'GT3',
       'Geolandar A/T G015', 'Geolandar A/T G016', 'Geolandar G92C',
       'Geolandar SUV G055', 'L607', 'Latitude Tour', 'Linam R 51',
       'MAP3', 'MS300', 'Manchester United', 'Milage X3', 'Milaze',
       'Milaze HD', 'Optimo K415', 'Optimo K715', 'Optimo ME02',
       'Potenza G3', 'Primacy 4ST', 'Primacy SUV', 'Ranger H/T',
       'S-Series S248', 'S-Series S322', 'S.Drive AS01',
       'Scorpion Verde All Season', 'SecuraDrive', 'Sincera835',
       'Sincera845', 'Taximaxx', 'Tornado', 'Turanza ER60',
       'Turanza T001', 'Turanza T005', 'UM 551', 'UM 787 LT', 'UX Royale',
       'Ultima NXT', 'Ultima Neo', 'Ultima Sport', 'Ultima XP',
       'Ultima XPC', 'Ultra Contact UC6', 'UltraContact UC6',
       'Victra I-Pro MA I-Pro', 'ZCC', 'ZCT', 'ZLO', 'ZLX', 'ZTX', 'ZV2K',
       'ZVTS', 'ZVTSM', 'ZVTV', 'Ziex ZE914 EcoRun'], dtype=object)

In [30]:
# Duraplus

id = df[df['Serial No.'] == 'Duraplus '].index
df.loc[id, 'Serial No.'] = df.loc[id, 'Serial No.'].str.replace(' ','')

df['Serial No.'].sort_values().unique()

array(['A348', 'AMAZER3G', 'Ainac 4G', 'Ainac 4GS', 'Altrust',
       'Amazer 3G Maxx', 'Amazer 4G', 'Amazer 4G Eco', 'Amazer 4G Life',
       'Amazer XL', 'Amazer4G', 'Apterra Cross', 'Apterra HP',
       'Aspire 4G', 'Assurance Armorgrip', 'Assurance Duraplus',
       'Assurance Duraplus 2', 'Assurance Triplemax',
       'Assurance Triplemax 2', 'AssuranceDuraplus', 'Azenis PT 722',
       'B-Series B250', 'B-Series B290', 'BluEarth AE50', 'BluEarth RV2',
       'BluEarth-GT AE51', 'Cinturato P1 Verde', 'Cinturato P4',
       'Cinturato P6', 'Cinturato P7', 'Comfort Contact CC5',
       'Comfort Contact CC6', 'Conti 4X4 Contact',
       'ContiComfort Contact CC5', 'ContiMax Contact MC5', 'Czar HP',
       'Czar Sports', 'DB E70B', 'Ducaro Hi-Miler', 'Duraplus',
       'Duraplus DP-M1', 'Dynapro HP (RA23)', 'Eagle F1 Directional 5',
       'Eagle F1 GSD3', 'Eagle NCT5', 'Earth-1 E400', 'EcoRun ZE914',
       'Ecopia EP150', 'Ecowing KH27', 'Efficient Grip SUV', 'Elanzo Nxt',
       'Elanzo Touring', 'Energy XM2', 'Excellence', 'FR500', 'FS100',
       'FuelSmart', 'GPS2', 'GT3', 'Geolandar A/T G015',
       'Geolandar A/T G016', 'Geolandar G92C', 'Geolandar SUV G055',
       'L607', 'Latitude Tour', 'Linam R 51', 'MAP3', 'MS300',
       'Manchester United', 'Milage X3', 'Milaze', 'Milaze HD',
       'Optimo K415', 'Optimo K715', 'Optimo ME02', 'Potenza G3',
       'Primacy 4ST', 'Primacy SUV', 'Ranger H/T', 'S-Series S248',
       'S-Series S322', 'S.Drive AS01', 'Scorpion Verde All Season',
       'SecuraDrive', 'Sincera835', 'Sincera845', 'Taximaxx', 'Tornado',
       'Turanza ER60', 'Turanza T001', 'Turanza T005', 'UM 551',
       'UM 787 LT', 'UX Royale', 'Ultima NXT', 'Ultima Neo',
       'Ultima Sport', 'Ultima XP', 'Ultima XPC', 'Ultra Contact UC6',
       'UltraContact UC6', 'Victra I-Pro MA I-Pro', 'ZCC', 'ZCT', 'ZLO',
       'ZLX', 'ZTX', 'ZV2K', 'ZVTS', 'ZVTSM', 'ZVTV', 'Ziex ZE914 EcoRun'],
      dtype=object)

In [31]:
# Ultra Contact UC6

id = df[df['Serial No.'] == 'Ultra Contact UC6'].index
df.loc[id, 'Serial No.'] = df.loc[id, 'Serial No.'].str.replace('Ultra Contact UC6','UltraContact UC6')
df['Serial No.'].sort_values().unique()

array(['A348', 'AMAZER3G', 'Ainac 4G', 'Ainac 4GS', 'Altrust',
       'Amazer 3G Maxx', 'Amazer 4G', 'Amazer 4G Eco', 'Amazer 4G Life',
       'Amazer XL', 'Amazer4G', 'Apterra Cross', 'Apterra HP',
       'Aspire 4G', 'Assurance Armorgrip', 'Assurance Duraplus',
       'Assurance Duraplus 2', 'Assurance Triplemax',
       'Assurance Triplemax 2', 'AssuranceDuraplus', 'Azenis PT 722',
       'B-Series B250', 'B-Series B290', 'BluEarth AE50', 'BluEarth RV2',
       'BluEarth-GT AE51', 'Cinturato P1 Verde', 'Cinturato P4',
       'Cinturato P6', 'Cinturato P7', 'Comfort Contact CC5',
       'Comfort Contact CC6', 'Conti 4X4 Contact',
       'ContiComfort Contact CC5', 'ContiMax Contact MC5', 'Czar HP',
       'Czar Sports', 'DB E70B', 'Ducaro Hi-Miler', 'Duraplus',
       'Duraplus DP-M1', 'Dynapro HP (RA23)', 'Eagle F1 Directional 5',
       'Eagle F1 GSD3', 'Eagle NCT5', 'Earth-1 E400', 'EcoRun ZE914',
       'Ecopia EP150', 'Ecowing KH27', 'Efficient Grip SUV', 'Elanzo Nxt',
       'Elanzo Touring', 'Energy XM2', 'Excellence', 'FR500', 'FS100',
       'FuelSmart', 'GPS2', 'GT3', 'Geolandar A/T G015',
       'Geolandar A/T G016', 'Geolandar G92C', 'Geolandar SUV G055',
       'L607', 'Latitude Tour', 'Linam R 51', 'MAP3', 'MS300',
       'Manchester United', 'Milage X3', 'Milaze', 'Milaze HD',
       'Optimo K415', 'Optimo K715', 'Optimo ME02', 'Potenza G3',
       'Primacy 4ST', 'Primacy SUV', 'Ranger H/T', 'S-Series S248',
       'S-Series S322', 'S.Drive AS01', 'Scorpion Verde All Season',
       'SecuraDrive', 'Sincera835', 'Sincera845', 'Taximaxx', 'Tornado',
       'Turanza ER60', 'Turanza T001', 'Turanza T005', 'UM 551',
       'UM 787 LT', 'UX Royale', 'Ultima NXT', 'Ultima Neo',
       'Ultima Sport', 'Ultima XP', 'Ultima XPC', 'UltraContact UC6',
       'Victra I-Pro MA I-Pro', 'ZCC', 'ZCT', 'ZLO', 'ZLX', 'ZTX', 'ZV2K',
       'ZVTS', 'ZVTSM', 'ZVTV', 'Ziex ZE914 EcoRun'], dtype=object)

In [32]:
# Comfort Contact CC5

id = df[df['Serial No.'] == 'Comfort Contact CC5'].index
df.loc[id, 'Serial No.'] = df.loc[id, 'Serial No.'].str.replace('Comfort Contact CC5','ContiComfortContact CC5')

id = df[df['Serial No.'] == 'ContiComfort Contact CC5'].index
df.loc[id, 'Serial No.'] = df.loc[id, 'Serial No.'].str.replace('ContiComfort Contact CC5','ContiComfortContact CC5')
df['Serial No.'].sort_values().unique()

array(['A348', 'AMAZER3G', 'Ainac 4G', 'Ainac 4GS', 'Altrust',
       'Amazer 3G Maxx', 'Amazer 4G', 'Amazer 4G Eco', 'Amazer 4G Life',
       'Amazer XL', 'Amazer4G', 'Apterra Cross', 'Apterra HP',
       'Aspire 4G', 'Assurance Armorgrip', 'Assurance Duraplus',
       'Assurance Duraplus 2', 'Assurance Triplemax',
       'Assurance Triplemax 2', 'AssuranceDuraplus', 'Azenis PT 722',
       'B-Series B250', 'B-Series B290', 'BluEarth AE50', 'BluEarth RV2',
       'BluEarth-GT AE51', 'Cinturato P1 Verde', 'Cinturato P4',
       'Cinturato P6', 'Cinturato P7', 'Comfort Contact CC6',
       'Conti 4X4 Contact', 'ContiComfortContact CC5',
       'ContiMax Contact MC5', 'Czar HP', 'Czar Sports', 'DB E70B',
       'Ducaro Hi-Miler', 'Duraplus', 'Duraplus DP-M1',
       'Dynapro HP (RA23)', 'Eagle F1 Directional 5', 'Eagle F1 GSD3',
       'Eagle NCT5', 'Earth-1 E400', 'EcoRun ZE914', 'Ecopia EP150',
       'Ecowing KH27', 'Efficient Grip SUV', 'Elanzo Nxt',
       'Elanzo Touring', 'Energy XM2', 'Excellence', 'FR500', 'FS100',
       'FuelSmart', 'GPS2', 'GT3', 'Geolandar A/T G015',
       'Geolandar A/T G016', 'Geolandar G92C', 'Geolandar SUV G055',
       'L607', 'Latitude Tour', 'Linam R 51', 'MAP3', 'MS300',
       'Manchester United', 'Milage X3', 'Milaze', 'Milaze HD',
       'Optimo K415', 'Optimo K715', 'Optimo ME02', 'Potenza G3',
       'Primacy 4ST', 'Primacy SUV', 'Ranger H/T', 'S-Series S248',
       'S-Series S322', 'S.Drive AS01', 'Scorpion Verde All Season',
       'SecuraDrive', 'Sincera835', 'Sincera845', 'Taximaxx', 'Tornado',
       'Turanza ER60', 'Turanza T001', 'Turanza T005', 'UM 551',
       'UM 787 LT', 'UX Royale', 'Ultima NXT', 'Ultima Neo',
       'Ultima Sport', 'Ultima XP', 'Ultima XPC', 'UltraContact UC6',
       'Victra I-Pro MA I-Pro', 'ZCC', 'ZCT', 'ZLO', 'ZLX', 'ZTX', 'ZV2K',
       'ZVTS', 'ZVTSM', 'ZVTV', 'Ziex ZE914 EcoRun'], dtype=object)

In [33]:
df2 = {'i': df['Serial No.'].sort_values().unique()}
df2 = pd.DataFrame(df2)
df2.tail(60)

                             i
50              Elanzo Touring
51                  Energy XM2
52                  Excellence
53                       FR500
54                       FS100
55                   FuelSmart
56                        GPS2
57                         GT3
58          Geolandar A/T G015
59          Geolandar A/T G016
60              Geolandar G92C
61          Geolandar SUV G055
62                        L607
63               Latitude Tour
64                  Linam R 51
65                        MAP3
66                       MS300
67           Manchester United
68                   Milage X3
69                      Milaze
70                   Milaze HD
71                 Optimo K415
72                 Optimo K715
73                 Optimo ME02
74                  Potenza G3
75                 Primacy 4ST
76                 Primacy SUV
77                  Ranger H/T
78               S-Series S248
79               S-Series S322
80                S.Drive AS01
81   Scorpion Verde All Season
82                 SecuraDrive
83                  Sincera835
84                  Sincera845
85                    Taximaxx
86                     Tornado
87                Turanza ER60
88                Turanza T001
89                Turanza T005
90                      UM 551
91                   UM 787 LT
92                   UX Royale
93                  Ultima NXT
94                  Ultima Neo
95                Ultima Sport
96                   Ultima XP
97                  Ultima XPC
98            UltraContact UC6
99       Victra I-Pro MA I-Pro
100                        ZCC
101                        ZCT
102                        ZLO
103                        ZLX
104                        ZTX
105                       ZV2K
106                       ZVTS
107                      ZVTSM
108                       ZVTV
109          Ziex ZE914 EcoRun

In [34]:
# df = df.drop(['Brand', 'Submodel', 'Const_type', 'Original Price'], axis=1, inplace=True)
df = df.drop(['Brand', 'Submodel', 'Const_type', 'Original Price'], axis=1)

print(df.shape)
df.head(10)

(4350, 10)

,Model,Tyre Brand,Serial No.,Type,Load Index,Tire_Width,Aspect_Rstio,Wheel_diam,Rating,Selling Price
0,Swift Dzire,JKTyre,Taximaxx,Tubeless,85,165,80,14,5.0,3255
1,Swift Dzire,CEAT,Milage X3,Tubeless,85,165,80,14,4.0,3406
2,Swift Dzire,Apollo,Amazer 4G Life,Tubeless,85,165,80,14,4.5,3490
3,Swift Dzire,Continental,Comfort Contact CC6,Tubeless,85,165,80,14,3.9,4484
4,Swift Dzire,GoodYear,Assurance Duraplus 2,Tubeless,85,165,80,14,4.2,3025
5,Swift Dzire,JKTyre,Tornado,Tubeless,85,165,80,14,4.3,3103
6,Swift Dzire,Firestone,FR500,Tubeless,85,165,80,14,3.9,3135
7,Swift Dzire,JKTyre,Elanzo Touring,Tubeless,85,165,80,14,4.1,3255
8,Swift Dzire,BridgeStone,B-Series B290,Tubeless,85,165,80,14,3.7,4250
9,Swift Dzire,BridgeStone,Turanza T005,Tubeless,85,165,80,14,3.8,4272

In [35]:
# df_tires = df[['Tyre Brand', 'Serial No.']].copy()
# print(df_tires.shape)
# df_tires.head(10)
# df_tires.to_csv('df_tires.csv', index=False)

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4350 entries, 0 to 4349
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Model          4350 non-null   object
 1   Tyre Brand     4350 non-null   object
 2   Serial No.     4350 non-null   object
 3   Type           4350 non-null   object
 4   Load Index     4350 non-null   int64
 5   Tire_Width     4350 non-null   int32
 6   Aspect_Rstio   4350 non-null   object
 7   Wheel_diam     4350 non-null   int32
 8   Rating         4350 non-null   float64
 9   Selling Price  4350 non-null   int32
dtypes: float64(1), int32(3), int64(1), object(5)
memory usage: 289.0+ KB

In [37]:
# Encode Nominal Variables
from sklearn.preprocessing import LabelEncoder

# 初始化LabelEncoder
le = LabelEncoder()

# Nominal Columns
col_to_le = ['Model',
      'Tyre Brand',
      'Serial No.',
      'Type',
      'Aspect_Rstio'
      ]

# 儲存編碼對照
le_dict = {}

# 擬合並轉換欄位

for col in col_to_le:
    df[col] = df[col].astype(str)
    df[col] = le.fit_transform(df[col])
    le_dict[col] = dict(zip(le.classes_, range(len(le.classes_))))



# 對每個欄位進行編碼
# for column in columns_to_encode:
#    le = LabelEncoder()
#    df[column] = le.fit_transform(df[column])
#    encoding_dict[column] = dict(zip(le.classes_, range(len(le.classes_))))

# 顯示結果

print("原始資料與編碼對照：")
for column, mapping in le_dict.items():
    print(f"{column} 對照：{mapping}")

原始資料與編碼對照：
Model 對照：{'800': 0, 'A-Star': 1, 'Alto': 2, 'Alto K10': 3, 'Baleno': 4, 'Celerio': 5, 'Celerio X': 6, 'Ciaz': 7, 'Dzire': 8, 'Eeco': 9, 'Ertiga': 10, 'Esteem': 11, 'Fronx': 12, 'Grand Vitara': 13, 'Grand Vitara 2003-2007 XI': 14, 'Gypsy': 15, 'Kizashi': 16, 'New Swift (2018)': 17, 'Omni': 18, 'Ritz': 19, 'SX4': 20, 'Stingray': 21, 'Swift': 22, 'Swift ': 23, 'Swift Deca': 24, 'Swift Dzire': 25, 'Swift Dzire 2008': 26, 'Vitara Brezza': 27, 'Wagon R': 28, 'Zen': 29, 'Zen Estilo': 30}
Tyre Brand 對照：{'Apollo': 0, 'BridgeStone': 1, 'CEAT': 2, 'Continental': 3, 'Falken': 4, 'Firestone': 5, 'GoodYear': 6, 'Hankook': 7, 'JKTyre': 8, 'Kumho': 9, 'MRF': 10, 'Maxxis': 11, 'Michelin': 12, 'Pirelli': 13, 'UltraMile': 14, 'Yokohama': 15}
Serial No. 對照：{'A348': 0, 'AMAZER3G': 1, 'Ainac 4G': 2, 'Ainac 4GS': 3, 'Altrust': 4, 'Amazer 3G Maxx': 5, 'Amazer 4G': 6, 'Amazer 4G Eco': 7, 'Amazer 4G Life': 8, 'Amazer XL': 9, 'Amazer4G': 10, 'Apterra Cross': 11, 'Apterra HP': 12, 'Aspire 4G': 13, 'Assurance Armorgrip': 14, 'Assurance Duraplus': 15, 'Assurance Duraplus 2': 16, 'Assurance Triplemax': 17, 'Assurance Triplemax 2': 18, 'AssuranceDuraplus': 19, 'Azenis PT 722': 20, 'B-Series B250': 21, 'B-Series B290': 22, 'BluEarth AE50': 23, 'BluEarth RV2': 24, 'BluEarth-GT AE51': 25, 'Cinturato P1 Verde': 26, 'Cinturato P4': 27, 'Cinturato P6': 28, 'Cinturato P7': 29, 'Comfort Contact CC6': 30, 'Conti 4X4 Contact': 31, 'ContiComfortContact CC5': 32, 'ContiMax Contact MC5': 33, 'Czar HP': 34, 'Czar Sports': 35, 'DB E70B': 36, 'Ducaro Hi-Miler': 37, 'Duraplus': 38, 'Duraplus DP-M1': 39, 'Dynapro HP (RA23)': 40, 'Eagle F1 Directional 5': 41, 'Eagle F1 GSD3': 42, 'Eagle NCT5': 43, 'Earth-1 E400': 44, 'EcoRun ZE914': 45, 'Ecopia EP150': 46, 'Ecowing KH27': 47, 'Efficient Grip SUV': 48, 'Elanzo Nxt': 49, 'Elanzo Touring': 50, 'Energy XM2': 51, 'Excellence': 52, 'FR500': 53, 'FS100': 54, 'FuelSmart': 55, 'GPS2': 56, 'GT3': 57, 'Geolandar A/T G015': 58, 'Geolandar A/T G016': 59, 'Geolandar G92C': 60, 'Geolandar SUV G055': 61, 'L607': 62, 'Latitude Tour': 63, 'Linam R 51': 64, 'MAP3': 65, 'MS300': 66, 'Manchester United': 67, 'Milage X3': 68, 'Milaze': 69, 'Milaze HD': 70, 'Optimo K415': 71, 'Optimo K715': 72, 'Optimo ME02': 73, 'Potenza G3': 74, 'Primacy 4ST': 75, 'Primacy SUV': 76, 'Ranger H/T': 77, 'S-Series S248': 78, 'S-Series S322': 79, 'S.Drive AS01': 80, 'Scorpion Verde All Season': 81, 'SecuraDrive': 82, 'Sincera835': 83, 'Sincera845': 84, 'Taximaxx': 85, 'Tornado': 86, 'Turanza ER60': 87, 'Turanza T001': 88, 'Turanza T005': 89, 'UM 551': 90, 'UM 787 LT': 91, 'UX Royale': 92, 'Ultima NXT': 93, 'Ultima Neo': 94, 'Ultima Sport': 95, 'Ultima XP': 96, 'Ultima XPC': 97, 'UltraContact UC6': 98, 'Victra I-Pro MA I-Pro': 99, 'ZCC': 100, 'ZCT': 101, 'ZLO': 102, 'ZLX': 103, 'ZTX': 104, 'ZV2K': 105, 'ZVTS': 106, 'ZVTSM': 107, 'ZVTV': 108, 'Ziex ZE914 EcoRun': 109}
Type 對照：{'Tube': 0, 'Tubeless': 1}
Aspect_Rstio 對照：{'0': 0, '55': 1, '60': 2, '65': 3, '70': 4, '80': 5}

In [38]:
import matplotlib.pyplot as plt
import seaborn as sns

X, y = df.iloc[: , : -1].values, df.iloc[: , -1].values
X.shape, y.shape

((4350, 9), (4350,))

In [39]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((3480, 9), (870, 9), (3480,), (870,))

In [62]:
scaler = StandardScaler()

X_train_ss = scaler.fit_transform(X_train)
X_test_ss = scaler.transform(X_test)

In [43]:
X_train_ss.shape, y_train.shape

((3480, 9), (3480,))

In [44]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import cross_val_score
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error
from xgboost import XGBRegressor

In [50]:
from xgboost import XGBRegressor

model = XGBRegressor()
model.fit(X_train_ss, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=None, n_jobs=None,
             num_parallel_tree=None, random_state=None, ...)

In [51]:
model.score(X_train_ss, y_train), model.score(X_test_ss, y_test)

(0.999882834857799, 0.9886133751198722)

In [52]:
y_pred = model.predict(X_test_ss)
print(f'R2 = {r2_score(y_test, y_pred)*100:.2f}')
print(f'MSE = {mean_squared_error(y_test, y_pred)}')
print(f'MAE = {mean_absolute_error(y_test, y_pred)}')

R2 = 98.86
MSE = 40160.56797240137
MAE = 24.07829168911638

In [63]:
# 模型存檔
import joblib

joblib.dump(model, 'Tire_Price_model.joblib')
joblib.dump(scaler, 'Tire_Price_scaler.joblib');

In [48]:
df.columns

Index(['Model', 'Tyre Brand', 'Serial No.', 'Type', 'Load Index', 'Tire_Width',
       'Aspect_Rstio', 'Wheel_diam', 'Rating', 'Selling Price'],
      dtype='object')

In [64]:
import requests

In [ ]:
import streamlit as st
import pandas as pd

# 指定 CSV 文件的路徑
csv_file_path = 'path/to/your/cars.csv'  # 請替換成你的文件路徑

# 讀取 CSV 文件並轉換成 DataFrame
df = pd.read_csv(csv_file_path)

# 確保有 'car brand' 和 'car model' 這兩個欄位
if 'car brand' in df.columns and 'car model' in df.columns:
    # 獲取所有的 car brand
    car_brands = df['car brand'].unique()

    # 選擇 car brand
    selected_brand = st.selectbox('Select Car Brand', car_brands)

    # 根據選擇的 car brand 獲取對應的 car model
    filtered_models = df[df['car brand'] == selected_brand]['car model'].unique()

    # 選擇 car model
    selected_model = st.selectbox('Select Car Model', filtered_models)

    # 顯示選擇的結果
    st.write(f'Selected Brand: {selected_brand}')
    st.write(f'Selected Model: {selected_model}')
else:
    st.error("CSV file must contain 'car brand' and 'car model' columns.")

In [ ]:
import requests

# 載入模型與標準化轉換模型
model = joblib.load('Tire_Price_model.joblib')
scaler = joblib.load('Tire_Price_scaler.joblib')

def get_exchange_rates():
    response = requests.get("https://api.exchangerate-api.com/v4/latest/INR")
    data = response.json()
    return data['rates']